### ISSUE TITLE
🐛 "Cross-site POST form submissions are forbidden"

### ISSUE THREAD

**Issue by beerinho** [SvelteLab/SvelteLab#197]
**Describe the bug**
I was trying to recreate an issue I was having locally regarding form submissions across multiple pages so I created an app with SvelteLab (love it by the way) and whenever I attempt a form submission I get a "Cross-site POST form submissions are forbidden" error (see below)

**To Reproduce**
Here is the repo - https://www.sveltelab.dev/2oirvsda624rftb
If you try to submit the form on the page you should see the error

**Expected behavior**
I expected to not get a cross site POST error - possibly another error due to the code, but not this error

**Screenshots**
<img width="1413" alt="image" src="https://github.com/SvelteLab/SvelteLab/assets/38084194/d5d11d03-b504-42ed-9d18-c0000be9922c">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 112.0.5615.137 (Official Build) (arm64)

**Comment by paoloricciuti** [comment]
Yeah unfortunately this is kind of a limitation of the webcontainers because to make them work we have to set specific headers that interfeer with the post submission.

However if you are willing to make them insecure you can disable csrf and they work

https://www.sveltelab.dev/24cl3ei62931v4u

To make this work you have to have the following `svelte.config.js`

```diff
import adapter from '@sveltejs/adapter-auto';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter(),
+		csrf: {
+			checkOrigin: false
+		}
	}
};

export default config;
```
